eureka:
  client:
    instance:
      preferIpAddress: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 9091
spring:
  application:
    name: EAMS
  main:
    banner-mode: 'OFF'
